---
- name: Add signing key
  tags: install
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc

- name: Add mongo repository
  tags: install
  apt_repository:
    repo: deb [arch=amd64] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
    state: present
    filename: mongodb-org-4.2.list

- name: Install mongodb package
  tags: install
  apt:
    name: mongodb-org
    update_cache: yes
    # update_cache_retries: 5
    # update_cache_retry_max_delay: 12

- name: Enable mongodb service
  tags: install
  service:
    name: mongod
    enabled: yes

- name: Start mongodb service
  tags: install
  service:
    name: mongod
    state: started
