---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add signing key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc

    - name: Add mongo repository
      apt_repository:
        repo: deb [arch=amd64] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
        state: present
        filename: mongodb-org-4.2.list

    - name: Install mongodb package
      apt:
        name: mongodb-org
        update_cache: yes
        update_cache_retries: 5
        update_cache_retry_max_delay: 12

    - name: Enable mongodb service
      service:
        name: mongod
        enabled: yes
